version: "3"
services:
  mysqlDB1:
    image: "mysql:5.7.27"
    ports:
      - "3306:3306"
    volumes:
      - "db-data:/var/lib/mysql"
      - "./init.sql:/docker-entrypoint-initdb.d/init-dump.sql"
    environment:
      - MYSQL_ROOT_PASSWORD=123456789*
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456789*      
    container_name: mysql_DB

volumes:
  db-data:

